function rad = interaction_radius(proxy_info, grid_info)
    % Returns the interaction radius in bin-index units, which is used to
    % determine which neighboring bins to spread to.
    %
    % proxy_info : struct with fields
    %   radius : scalar
    %     The radius of the proxy points in physical units.
    %
    % grid_info : struct with fields
    %   nspread : scalar
    %     The number of points in the spreading box along one dimension.
    %   dx : scalar
    %     The grid spacing in physical units.
    

    % This inflation amount is validated by inspecting the figure generated by 
    % test_neighbor_template_2d_1 part 3.
    inflation = sqrt(grid_info.dim) * grid_info.rpad * grid_info.dx;

    rad = ceil( (proxy_info.radius + inflation)/(grid_info.nbinpts * grid_info.dx));
end